- name: Install Latest Docker and Kubernetes with Calico
  hosts: all
  gather_facts: true
  become: true  
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
   
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    

    - name: Add Kubernetes GPG key
      #command: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      
    - name: Add Kubernetes APT repository
     # lineinfile:
      #  path: /etc/apt/sources.list.d/kubernetes.list
      #  line: "deb https://apt.kubernetes.io/ kubernetes-xenial main" 
      #  state: present
        shell : echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt repository again
      apt:
        update_cache: yes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold Kubernetes components at current version
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Initialize the Kubernetes master
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      when: inventory_hostname == groups['master'][0]


    - name: Set up kubectl for the regular user
      block:
        - name: Create .kube directory
          file:
            path: ~/.kube
            state: directory
            mode: '0755'

        - name: Copy admin.conf to .kube/config
          command: cp -i /etc/kubernetes/admin.conf ~/.kube/config
          args:
            removes: ~/.kube/config

        - name: Change ownership of .kube/config
          command: chown $(id -u):$(id -g) ~/.kube/config

    - name: Install Calico Pod Network Add-On
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: inventory_hostname == groups['master'][0]

    - name: Join worker nodes to the cluster
      command: kubeadm join {{ hostvars[groups['master'][0]]['ansible_host'] }}:6443 --token {{ hostvars[groups['master'][0]]['kubeadm_token'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['master'][0]]['ca_cert_hash'] }}
      when: inventory_hostname in groups['worker']

  post_tasks:
    - name: Show nodes in the cluster
      command: kubectl get nodes
      when: inventory_hostname == groups['master'][0]
