- hosts: k8s_workers
  become: yes
  vars:
    ansible_ssh_private_key_file: /path/to/your/private/key.pem  # Update with your key path
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install PHP and related packages
      apt:
        name:
          - php
          - php-cli
          - php-fpm
          - php-mysql
        state: present
        update_cache: yes
    
    - name: Ensure PHP-FPM is running
      service:
        name: php7.4-fpm
        state: started
        enabled: yes
