- name: Install Latest Docker and Kubernetes with Calico
  hosts: all
  gather_facts: true
  become: true  
  tasks:
    
    - name: Read the kubeadm join command from file
      slurp:
        src: /root/cluster_initialized.txt
      register: kubeadm_join_file
      when: inventory_hostname == groups['k8s_master'][0]

    - name: Convert file content from base64 to text
      set_fact:
        kubeadm_join_command: "{{ kubeadm_join_file.content | b64decode }}"
      when: inventory_hostname == groups['k8s_master'][0]

    - name: Extract the token from the kubeadm join command
      set_fact:
        kubeadm_token: "{{ (kubeadm_join_command | regex_search('--token ([a-zA-Z0-9\\.\\-]+)', '\\1')) | first }}"
      when: kubeadm_join_command is defined and inventory_hostname == groups['k8s_master'][0]

    - name: Extract the hash from the kubeadm join command
      set_fact:
        kubeadm_cert_hash: "{{ (kubeadm_join_command | regex_search('--discovery-token-ca-cert-hash sha256:([a-f0-9]+)', '\\1')) | first }}"
      when: kubeadm_join_command is defined and inventory_hostname == groups['k8s_master'][0]

    - name: Debug the extracted token and hash
      debug:
        msg: "Extracted Token: {{ kubeadm_token }}, Extracted Cert Hash: sha256:{{ kubeadm_cert_hash }}"
      when: kubeadm_token is defined and kubeadm_cert_hash and inventory_hostname == groups['k8s_master'][0]

    - name: Set up kubectl for the regular user
      block:
        - name: Create .kube directory
          file:
            path: ~/.kube
            state: directory
            mode: '0755'
          when: inventory_hostname == groups['k8s_master'][0]


        - name: Copy admin.conf to .kube/config
          command: cp -i /etc/kubernetes/admin.conf ~/.kube/config
          when: inventory_hostname == groups['k8s_master'][0]
          #args:
            #removes: ~/.kube/config

        - name: Change ownership of .kube/config
          shell: chown $(id -u):$(id -g) ~/.kube/config
          when: inventory_hostname == groups['k8s_master'][0]


    - name: Install Calico Pod Network Add-On
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
      when: inventory_hostname == groups['k8s_master'][0]

    - name: Join worker nodes to the cluster
      command: kubeadm join {{ hostvars[groups['k8s_master'][0]].inventory_hostname }}:6443 --token {{ hostvars[groups['k8s_master'][0]].kubeadm_token }} --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_master'][0]].kubeadm_cert_hash }} --cri-socket unix:///var/run/cri-dockerd.sock
      when: inventory_hostname in groups['k8s_worker']
    
  post_tasks:
    - name: Show nodes in the cluster
      command: kubectl get nodes
      when: inventory_hostname == groups['k8s_master'][0]
