- name: Install Latest Docker and Kubernetes with Calico
  hosts: all
  gather_facts: true
  become: true  
  tasks:

     - name: Slurp the file from the remote machine
       slurp:
        src: /root/cluster_initialized.txt  # Replace with the actual file path
       register: file_content
       when: inventory_hostname == groups['k8s_master'][0]

     - name: Decode the base64 content and extract the token and cert hash
       set_fact:
         kubeadm_token: "{{ decoded_content | regex_search('--token\\s+([a-z0-9]{6}\\.[a-z0-9]{16})') | first }}"
         kubeadm_cert_hash: "{{ decoded_content | regex_search('--discovery-token-ca-cert-hash\\s+sha256:([a-f0-9]+)') | first }}"
       vars:
          decoded_content: "{{ file_content.content | b64decode }}"
       when: file_content is defined and inventory_hostname == groups['k8s_master'][0]

     - name: Debug the content of the file
       debug:
         msg: "{{ decoded_content }}"
       when: file_content is defined and inventory_hostname == groups['k8s_master'][0]

        
     - name: Debug extracted values
       debug:
        msg: "Extracted Token: {{ kubeadm_token }}, Extracted Cert Hash: {{ kubeadm_cert_hash }}"
       when: kubeadm_token is defined and kubeadm_cert_hash is defined and inventory_hostname == groups['k8s_master'][0]

    
     - name: Set up kubectl for the regular user
       block:
         - name: Create .kube directory
           file:
             path: ~/.kube
             state: directory
             mode: '0755'
           when: inventory_hostname == groups['k8s_master'][0]


         - name: Copy admin.conf to .kube/config
           command: cp -i /etc/kubernetes/admin.conf ~/.kube/config
           when: inventory_hostname == groups['k8s_master'][0]
           #args:
             #removes: ~/.kube/config

         - name: Change ownership of .kube/config
           shell: chown $(id -u):$(id -g) ~/.kube/config
           when: inventory_hostname == groups['k8s_master'][0]


     - name: Install Calico Pod Network Add-On
       command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
       when: inventory_hostname == groups['k8s_master'][0]

     - name: Join worker nodes to the cluster
       command: kubeadm join {{ hostvars[groups['k8s_master'][0]].inventory_hostname }}:6443 --token {{ hostvars[groups['k8s_master'][0]].kubeadm_token }} --discovery-token-ca-cert-hash {{ hostvars[groups['k8s_master'][0]].kubeadm_cert_hash }} --cri-socket unix:///var/run/cri-dockerd.sock
       when: inventory_hostname in groups['k8s_worker']
    
  post_tasks:
    - name: Show nodes in the cluster
      command: kubectl get nodes
      when: inventory_hostname == groups['k8s_master'][0]
